In [4]:
import numpy as np
import math

n = 5
A = np.array([
    [0  , 1/5, 1/2 , 1/3, 0  ], 
    [1/5, 0  , 1/2 , 0  , 0  ], 
    [1/2, 1/2, 0   , 1/2, 0  ], 
    [1/3, 0  , 1/2 , 0  , 1/4], 
    [0  , 0  , 0   , 1/4, 0  ]
])

B = []
for i in A:
    B.append([])
    for j in i:
        if j == 0:
            B[-1].append(0)
        else:
            B[-1].append(1/j)

B = np.array(B)

x = []
x.append(np.array([1, 0, 0, 0, 0]))

v_bar=[]
for i in range(2):
    v_bar.append([1 for j in range(5)])
for i in range(8):
    v_bar.append([1, 1, 1, 1, 1])

M = 1000


In [5]:
# with fire processing time
# unfuncitonal
x = []
x.append(np.array([1, 0, 0, 0, 0]))
# process = np.zeros((n, n))
q = [2, 1, 3, 2, 1, 0]
process = [[-q[i] for j in range(5)] for i in range(5)]
for i in range(5):
    process[i][i] = 0
# print([A[:k] for k in range(5)])

chromosome = [0, 0, 1, 1, 0, 1, 5, 2, 3, 0, 1, 4]
# print(process)
for i in range(10):
    process += np.multiply(A, x[-1])
#     print(process)
    x.append([max(min(math.floor(np.max(process[k, :]))+x[-1][k], 1), 0) for k in range(5)])
    print(i+1, x[-1])

x = np.array(x)
# print(x)
# print(list(x[:, 1]).index(1))

1 [1, 0, 0, 0, 0]
2 [1, 0, 0, 0, 0]
3 [1, 0, 0, 0, 0]
4 [1, 0, 0, 0, 0]
5 [1, 0, 0, 0, 0]
6 [1, 0, 0, 0, 0]
7 [1, 0, 0, 0, 0]
8 [1, 0, 1, 0, 0]
9 [1, 0, 1, 0, 0]
10 [1, 1, 1, 1, 0]


In [6]:
# no fire processing time
# well funcitonal
x = []
x.append(np.array([1, 0, 0, 0, 0]))
process = np.zeros((n, n))
# print([A[:k] for k in range(5)])

chromosome = [0, 0, 1, 1, 0, 1, 5, 2, 3, 0, 1, 4]

for i in range(10):
    process += np.multiply(A, x[-1])
#     print(process)
    x.append([min(math.floor(np.max(process[k, :]))+x[-1][k], 1) for k in range(5)])
    print(i+1, x[-1])

x = np.array(x)
print(x)
print(list(x[:, 1]).index(1))

1 [1, 0, 0, 0, 0]
2 [1, 0, 1, 0, 0]
3 [1, 0, 1, 1, 0]
4 [1, 1, 1, 1, 0]
5 [1, 1, 1, 1, 0]
6 [1, 1, 1, 1, 0]
7 [1, 1, 1, 1, 1]
8 [1, 1, 1, 1, 1]
9 [1, 1, 1, 1, 1]
10 [1, 1, 1, 1, 1]
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 0 0]
 [1 0 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
4


In [7]:
# wrong version
# ignore the effect of all in-degree
for i in range(10):
    x.append(x[-1] + x[-1].astype(int).dot(A+np.eye(5)))
    x[-1] = np.multiply(v_bar[i], x[-1])
    for j in range(len(x[-1])):
        if(x[-1][j] > 1) :
            x[-1][j] = 1

for i in x:
#     print([math.floor(j) for j in i])
    print(i)

print()
for i in x:
    print([math.floor(j) for j in i])


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [22]:
for i in range(1, 6):
    print(i)

1
2
3
4
5
